### ISSUE TITLE
Fastq file name recognition - shuffleSplitReads.pl

### ISSUE THREAD

**Issue by alexwailan** [lskatz/lyve-SET#80]
The shuffleSplitReads.pl script to interleaves paired-end reads to have one file per sample.

Unfortunately due to the code itself it will no recognise/support a ‘SAMPLE_R1.fastq.gz’ format when identifying the read number from “the rest”.  

The counter for now is to rename the fastq files ‘SAMPLE_R1_.fastq.gz’ or ‘SAMPLE_1.fastq.gz’.

I prefer the latter and achieve the renaming by the following code:
for x in *.gz; do mv "$x" "$(echo "$x" | sed -e 's/_R/_/g')";done 
i.e. replace the _R with _

**Comment by lskatz** [comment]
It looks like I made this too difficult to change right now because of this code

    if($therest=~/_R([12])_/){
      $readNumber=$1;
    } elsif($therest=~/_([12])\.f/){
      $readNumber=$1;
    } else {
      die "ERROR: could not parse the read number from file $filename in the second part of the file =>$therest<=";
    }

In the code, it expects the filenames to match either `_R[12]_` or `_[12].f` which isn't going to work for your naming scheme.  At this time, I am comfortable at least documenting it here in the issues, and I am glad you brought it up.  I recommend for the time being that users stick with the `_1.fastq.gz` naming scheme or the standard `_R1_` naming scheme.

**Comment by alexwailan** [comment]
Thanks Lee for the quick reply! All agree with your response! Keep up the good work!
