### ISSUE TITLE
An option for not complete deletion

### ISSUE THREAD

**Issue by lskatz** [lskatz/lyve-SET#9]
Per the CFSAN pipeline's PeerJ paper, it seems like pairwise deletion might give longer branch lengths but might yield a more confident topology.  I need to put in an option to leave ambiguities (Ns) in the multiple sequence alignment so that RAxML has to deal with them.

**Comment by EpiDemos82** [comment]
Can you post the link to the paper?  Removing Ns will affect branch lengths
since the ML algorithm uses constant sites in the likelihood function;
however, RAxML was suppose to have addressed this with the implementation
of the ascertainment bias correction "ASC_GTRGAMMA" option in the model
selection.  I am interested to see if they included this in the
comparison.  Also, at the end of the day, how much does the variation in
branch lengths affect your interpretation of the relationship between two
isolates?

On Tue, Feb 3, 2015 at 9:39 AM, Lee Katz <notifications@github.com> wrote:

> Perl the CFSAN pipeline's PeerJ paper, it seems like pairwise deletion
> might give longer branch lengths but might yield a more confident topology.
> I need to put in an option to leave ambiguities (Ns) in the multiple
> sequence alignment so that RAxML has to deal with them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lskatz/lyve-SET/issues/9>.
>



-- 
Taj Azarian, MPH
TajAzari@gmail.com

**Comment by lskatz** [comment]
Sure!  I'm not going to review a paper on this site but here is the paper.  https://peerj.com/articles/620/

**Comment by lskatz** [comment]
* I put in the option for not complete deletion
* RAxML8 is now installed with make-install
* `set_process.pl` and `launch_set.pl` create a "pairwise deletion" informative alignment instead of a "complete deletion"
